### ISSUE TITLE
[Server] Content uploaded to IPFS is incomplete

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-server#2672] opened 2022-08-10 02:37 UTC
### Tasks
- [x] Find out the problem caused by `server` or `formatter`
- [x] Update codebase if spot the bug

### References
- [Slack](https://mattersnews.slack.com/archives/GA0R09FHN/p1659947271745689)

**Comment by gary02** [comment] 2022-08-10 06:39
the slack link in ref: ![2022-08-10-143704_1620x315_scrot](https://user-images.githubusercontent.com/13580441/183832347-796446c7-8b15-4ffb-b111-3626d34c72c1.png)

**Comment by gary02** [comment] 2022-08-15 07:06
The problem is caused by `formatter` which incorrectly format  `iframe` tags [using  self-closing format](https://stackoverflow.com/questions/27545757/why-is-a-self-closing-iframe-tag-preventing-further-dom-elements-to-be-displayed):
```javascript
const { makeHtmlBundle } = require('@matters/matters-html-formatter');

const { bundle } = await makeHtmlBundle({
  title: "test article",
  author: {
    name: "test-user",
    link: {
      url: "https://matters.news/@test-user",
      text: "Test User",
    },
  },
  content: `<iframe loading="lazy" src="https://www.youtube.com/"></iframe>`,
  paymentPointer: "$pay-me",
  encrypt: false
});

console.log(bundle[0].content.toString());
//  ... <html><head/><body><iframe loading="lazy" src="https://www.youtube.com/"/></body></html>  ...
```

**Comment by robertu7** [comment] 2022-08-15 07:43
> the slack link in ref: ![2022-08-10-143704_1620x315_scrot](https://user-images.githubusercontent.com/13580441/183832347-796446c7-8b15-4ffb-b111-3626d34c72c1.png)

Added you to the Slack channel.

**Closed** 2022-08-24 09:33 UTC
Labels: bug
